language: java
jdk: oraclejdk8
sudo: false
dist: trusty
install: true
addons:
  sonarcloud:
    organization: raouf25-github
    token:
      secure: YuUylAC+te6QfRPx3K9luCZggy0/AZuXxU/Ja0/RZSnYWkTlddu5zhERDlDszQ4MabxydpJE04b8it8jpRROGbqrl3EBb8xJaKX6H138TAUxkwSzpzGFuB0JE4J/6Emggo+TjRe90tb/tTbMmunskv4NzZeTnhn08VlkDt3ANRIiYXtCXcFCbAiwAZWYzcJFCsQHwMOOkvlCs34xK1GeIQpBKt0Wbd87r5nzrFNq7pBIL1xHiLQG3i6a51An53UdyMzz4qaziLAbpMxRjLPyzJu+niremVTWHlULxnIA9dHIiBwDYX8/g/SFS/iGWrD0lP/T7LSaUCt8BMsCaih/lxr8u+mc4DeotNBooblOjiZcfHpPty52bCXAmWVBYgYEx2mCqWPkUprauB7ID7Evm+7qiCatAyWpCbG78/A6oArCGLDR86hSo9FAjyH8qK+wO2nedEcV7T2gAwVAv+GCKt/yBph887DLDffwQImiVItb6eCqfhGMyp+f/YQPk9JlLROvHZ2Uj4h/LfrdFJgz8SjhWbk1jewPOTKbzeqBcwea5ouBkTG/cs7UF4xiuQjDU6QdMdG3mDcLOoUF5P/piMAFflkLvMeZ6xw/sxsTOrim8RiHk9K/4lUvdY5vZvGHKryUQHlnTkbgUJWHOm4oSpk03TEtih+MPiiN9tOatyg=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
- mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
notifications:
  email:
    recipients:
    - makhlouf.raouf+travis@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: LITEYNS6nFJg9uzxnMcgZd/mno0CDO26B+brLp8GbmX2116bFg9MEVfbnjyBMJmLkeYjrx6b5PKrsfy9h7rZjt1lxeAoAcaV/LjkaLJ5cnmubXEkO8F2KH4toA+i1xc2WKtoTXhRr5IDZt20g1NZRJk8L/OcVSDWf2MKCfgORV0TeLaSb2JWlVET7EaKoVDccLFAdbz0TSzzS00JT0f+A05vc+N9Hq9ScVsV6Sqv1KCKJk3IPbraIKKt1nc/7SPTPtLAsnjF+MfXFSgudM9rOoEGSK6mOYkuMmj58IFn6ZOQxQVMEb7znKYLkBKU9EJlkqJSdp1Z06L2BersNkfQZNKPjf8kz5INDCXf2WFmi23NGZhpMupftJxlyroebc+QlL0H//rAY3kUFMe56qJJCkuL4qaMF5YiQqRnAtB10FKu1eDt0OlGJ4mQeTE9THTGoS1qz1ZJoHscqBKLdQ70oJInXr/jikIE1L57hPXrEbeyvaAT/x+b32IuglHh6F65gdOmAFrj2Mx75duk9aTEyuobuXZwN3lZKrD9G0/YV0x+Z1voufvAdQBMq3pHQC/yIiR7rbhNsGf1VV5fY0D5QS/lsBEte8YNpCs3PAcb6L0NtJnHWqp9ox6GpUsh7j3N7xjCupEL2Z/reBR9n5I4zdVzHuhZ01Mb9/INYhapS6E=
  app: raouf-restful-services
