language: java
jdk: oraclejdk8
sudo: false
install: true
addons:
  sonarcloud:
    organization: raouf25-github
    token:
      secure: P/a3wfdHyzkK/sOBRPP5R20AuoZxxUzF10jl3rMhOEC/D991FvYmfSdNA+11DnmLOLqwRMFtBl85Y/Mnr6AkqIxVmES1f5KPj5iicSNbQZ6mFXxE0OB5U7LjuFf6mJutOCGL7LDhImILH+3L87jsEltZmjj2KsSfRUftaOlBgydVuMNrAXvclt8zblKfSWg3fc2Ci8kq6mEm5Tqv2xWrZCUYglZSZucUW9pmwSaiZHo4nXF4DqDAdAFw7Cp9urCsARnCPp9tuekR+VXvA9E5XjarAKcp0Lsrk2BKCU5uAdqEVMEHqFnCTsUN4daEpLlBBTfajh+2jnxIkIXteFBMeYDbsVGdT9Vxux49hkW0TWDGC6Nlg8pTiJOLSelsEJbwCBwTG0ehVtgWX5Gj6Rw65VrCSdYBbrHT9lsYe/Ssu2PbICPnhQBCFEOerRZAcb83HW+53HADS+W6H4jOU7jqItYDkARjngEpMLD2tA/O1jBTsBfwf9sSA0kG3AvKxYjG3AOU5ACjROuQNirAHD9DjDHDPuyypNYEzjI3BuzJZI9n029Q+3ZxzCo6aZvTnw7yTSxyPoYA0AvlL1AAA1tf/+01afel9R2sseV/15L+liTKZ8HQCXKgeSvdsd3+aEQJxnoYimylGCe8Sd7DIImr9OBPXMJWPFVFTxDiwe1qkDs=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
- mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
deploy:
  provider: heroku
  api_key:
    secure: AjbfI1Hh+TAHJQ2A6me7keASnnOPm7X1xdod4HNcgMiXIs9Aq6SC0JwBdAtj9mXA4umjNIEK7eNSabpFuzjQs5w42QL0SEef7LGgAATUvVOiT0i3yIVXkz6NjcSl4gP9raJwwRxqr73PLdTQ0sbpQw0EH+tcToGXgNsDSWG/Zz/VVXoT6/yIoPz1QUWisVfed9OUw4vEl+joNv8E82VrxANpRBZi/0h6ouEWk0ICdntINwzdCErT4urtMGzr6kULGyhTZiLt5JQ11qfxCKtqE61HTxFkIqoDBW8S+vsrltW4cU4ibD4gK2aHYjGsbsDXY+YuBLiInDztaABfq0MYiPpzG+omggf9bpxYc7xVFHtjMEzFC/R+eyTufchvz+QB/LYKu6vXr4GdKYYkX2Rhq7regeuAsTwy+DQ6kop2HnLXP0ihVQcl1sFWh+N8CN6NRHUd5Fk4YF9vigt/xkhfwBlMIdWc5fusDdOpaZW47htYD90RnD0CXmVMGILcPN9MJKxOAiLXLnxAevK7LhX69xOzL/o/3gN80GEgcsDaiEeq/NX/gO3Il3r2QfL2bVWsTMLdSCcQ4wwmasC1iqcR2trNUcOZNLFqXedCmXgtfMVvtbej4A3EapGiCHU/fMhoVfDAhUtmhllI3OFE74DOwuug/9aUEDwqHjnWhuNqLV0=
  app: raouf-restful-services
